In [2]:
import pandas as pd
import numpy as np
import keras
from keras.models import Model
from keras.layers import *
from keras import optimizers
from keras.utils import to_categorical

In [4]:
df_train = pd.read_csv(r'D:\intellipaat ds ai ml\DS@AI\6 AI\000 - self paced\Module 4 - Modelling with Keras\Dataset\train.csv')
df_test = pd.read_csv(r'D:\intellipaat ds ai ml\DS@AI\6 AI\000 - self paced\Module 4 - Modelling with Keras\Dataset\test.csv')

In [5]:
df_train.head() # 784 features, 1 label

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
df_features = df_train.iloc[:, 1:785]
df_label = df_train.iloc[:, 0]

X_test = df_test.iloc[:, 0:784]

print(X_test.shape)

(28000, 784)

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_cv, y_train, y_cv = train_test_split(df_features, df_label, 
                                                test_size = 0.2,
                                                random_state = 1212)

X_train = X_train.to_numpy().reshape(33600, 784) #(33600, 784)    
X_cv = X_cv.to_numpy().reshape(8400, 784) #(8400, 784)

X_test = X_test.to_numpy().reshape(28000, 784)

# X_train = X_train.as_matrix().reshape(33600, 784) #(33600, 784)    as_matrix deprecated. so use to_numpy()
# X_cv = X_cv.as_matrix().reshape(8400, 784) #(8400, 784)

# X_test = X_test.as_matrix().reshape(28000, 784)

In [8]:
print((min(X_train[1]), max(X_train[1])))

(np.int64(0), np.int64(255))

In [9]:
X_train[0]  #1st image in x_train which shows pixel values (0-255) of the 1st image  .same for 2nd- [1], 3rd- [2]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   2,  56, 140, 195,
       155, 155,  12,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  30, 192, 254,
       254, 254, 254, 254, 103,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  11, 103, 253,
       254, 254, 254, 254, 254, 254,  55,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 135,
       254, 254, 254, 242, 244, 254, 254, 254,  20,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0, 130, 179, 179, 138,  48, 196, 254, 254, 170,   6,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   1, 123, 254, 254, 242,  37,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   6, 254, 254, 254, 196,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 155, 254, 254,
       243,  31,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  77, 243,
       254, 249,  77,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
       249, 254, 254, 180,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         1, 120, 254, 254, 253,  98,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,  41, 254, 254, 254, 131,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   6, 131, 254, 254, 205,  15,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,  86, 254, 254, 241,  69,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,  15, 208, 254, 254,  77,   0,  40,
       126, 153, 176,  55,  12,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0, 132, 254, 254, 254,  89,
       122, 227, 254, 254, 254, 229,  82,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,  84, 253, 254, 254,
       254, 239, 254, 254, 252, 192,  71,  14,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   8, 203, 254,
       254, 254, 254, 254, 254, 233,  76,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 100,
       254, 254, 254, 254, 254, 228,  88,   7,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   5,  84, 166, 254, 183,  55,  23,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0])

In [10]:
# Feature Normalization (pixel values are b/w 0 to 255) 
X_train = X_train.astype('float32'); X_cv= X_cv.astype('float32'); X_test = X_test.astype('float32')
X_train /= 255; X_cv /= 255; X_test /= 255
# the values in each row are pixel intensity values, which typically range from 0 to 255 for grayscale images:

# 0 → black

# 255 → white

# values in between → different shades of gray

In [11]:
# Convert labels to One Hot Encoded
num_digits = 10
y_train =to_categorical(y_train, num_digits)
y_cv = to_categorical(y_cv, num_digits)

In [12]:
# Printing 2 examples of labels after conversion
print(y_train[0]) # 2
print(y_train[3]) # 7

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]

In [13]:
# Input Parameters
n_input = 784 # number of features
n_hidden_1 = 300
n_hidden_2 = 100
n_hidden_3 = 100
n_hidden_4 = 200
num_digits = 10

In [14]:
Inp = Input(shape=(784,))
x = Dense(n_hidden_1, activation='relu', name = "Hidden_Layer_1")(Inp) #Inp → Hidden_Layer_1 → x 
x = Dense(n_hidden_2, activation='relu', name = "Hidden_Layer_2")(x) #chain of connections is created by repeatedly calling layers with ()
x = Dense(n_hidden_3, activation='relu', name = "Hidden_Layer_3")(x)
x = Dense(n_hidden_4, activation='relu', name = "Hidden_Layer_4")(x)
output = Dense(num_digits, activation='softmax', name = "Output_Layer")(x)

In [15]:
# Our model would have '6' layers - input layer, 4 hidden layer and 1 output layer
model = Model(Inp, output)
# model = Model(inputs =Inp, outputs =output)
model.summary() # We have 297,910 parameters to estimate

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_1 (Dense)          │ (None, 300)            │       235,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_2 (Dense)          │ (None, 100)            │        30,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_3 (Dense)          │ (None, 100)            │        10,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_4 (Dense)          │ (None, 200)            │        20,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Output_Layer (Dense)            │ (None, 10)             │         2,010 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 297,910 (1.14 MB)

 Trainable params: 297,910 (1.14 MB)

 Non-trainable params: 0 (0.00 B)

In [16]:
# Insert Hyperparameters
learning_rate = 0.1
training_epochs = 20
batch_size = 100
sgd = optimizers.SGD(learning_rate=learning_rate)

In [17]:
# We rely on the plain vanilla Stochastic Gradient Descent as our optimizing methodology
model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])

In [18]:
history1 = model.fit(X_train, y_train,
                     batch_size = batch_size,
                     epochs = training_epochs,
                     verbose = 2,
                     validation_data=(X_cv, y_cv))

Epoch 1/20
336/336 - 31s - 92ms/step - accuracy: 0.5516 - loss: 1.7125 - val_accuracy: 0.8021 - val_loss: 0.8574
Epoch 2/20
336/336 - 14s - 41ms/step - accuracy: 0.8453 - loss: 0.5888 - val_accuracy: 0.8760 - val_loss: 0.4389
Epoch 3/20
336/336 - 11s - 33ms/step - accuracy: 0.8870 - loss: 0.3939 - val_accuracy: 0.8993 - val_loss: 0.3491
Epoch 4/20
336/336 - 10s - 29ms/step - accuracy: 0.9048 - loss: 0.3284 - val_accuracy: 0.9080 - val_loss: 0.3134
Epoch 5/20
336/336 - 12s - 36ms/step - accuracy: 0.9158 - loss: 0.2907 - val_accuracy: 0.9174 - val_loss: 0.2811
Epoch 6/20
336/336 - 10s - 29ms/step - accuracy: 0.9237 - loss: 0.2632 - val_accuracy: 0.9250 - val_loss: 0.2538
Epoch 7/20
336/336 - 11s - 32ms/step - accuracy: 0.9296 - loss: 0.2406 - val_accuracy: 0.9273 - val_loss: 0.2447
Epoch 8/20
336/336 - 10s - 30ms/step - accuracy: 0.9353 - loss: 0.2223 - val_accuracy: 0.9337 - val_loss: 0.2226
Epoch 9/20
336/336 - 11s - 32ms/step - accuracy: 0.9396 - loss: 0.2058 - val_accuracy: 0.9371 - val_loss: 0.2119
Epoch 10/20
336/336 - 11s - 31ms/step - accuracy: 0.9429 - loss: 0.1924 - val_accuracy: 0.9408 - val_loss: 0.2013
Epoch 11/20
336/336 - 11s - 33ms/step - accuracy: 0.9480 - loss: 0.1792 - val_accuracy: 0.9415 - val_loss: 0.1986
Epoch 12/20
336/336 - 9s - 27ms/step - accuracy: 0.9501 - loss: 0.1682 - val_accuracy: 0.9454 - val_loss: 0.1822
Epoch 13/20
336/336 - 11s - 32ms/step - accuracy: 0.9539 - loss: 0.1586 - val_accuracy: 0.9467 - val_loss: 0.1787
Epoch 14/20
336/336 - 11s - 31ms/step - accuracy: 0.9573 - loss: 0.1495 - val_accuracy: 0.9504 - val_loss: 0.1702
Epoch 15/20
336/336 - 10s - 30ms/step - accuracy: 0.9587 - loss: 0.1420 - val_accuracy: 0.9499 - val_loss: 0.1646
Epoch 16/20
336/336 - 6s - 18ms/step - accuracy: 0.9608 - loss: 0.1340 - val_accuracy: 0.9527 - val_loss: 0.1588
Epoch 17/20
336/336 - 9s - 28ms/step - accuracy: 0.9624 - loss: 0.1275 - val_accuracy: 0.9524 - val_loss: 0.1580
Epoch 18/20
336/336 - 7s - 20ms/step - accuracy: 0.9657 - loss: 0.1214 - val_accuracy: 0.9557 - val_loss: 0.1500
Epoch 19/20
336/336 - 9s - 27ms/step - accuracy: 0.9671 - loss: 0.1159 - val_accuracy: 0.9558 - val_loss: 0.1487
Epoch 20/20
336/336 - 6s - 19ms/step - accuracy: 0.9678 - loss: 0.1103 - val_accuracy: 0.9577 - val_loss: 0.1436

In [20]:
# Using adam optimizer
Inp = Input(shape=(784,))
x = Dense(n_hidden_1, activation='relu', name = "Hidden_Layer_1")(Inp)
x = Dense(n_hidden_2, activation='relu', name = "Hidden_Layer_2")(x)
x = Dense(n_hidden_3, activation='relu', name = "Hidden_Layer_3")(x)
x = Dense(n_hidden_4, activation='relu', name = "Hidden_Layer_4")(x)
output = Dense(num_digits, activation='softmax', name = "Output_Layer")(x)

# We rely on ADAM as our optimizing methodology
adam = keras.optimizers.Adam(learning_rate=learning_rate)
model2 = Model(Inp, output)

model2.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [21]:
history2 = model2.fit(X_train, y_train,
                      batch_size = batch_size,
                      epochs = training_epochs,
                      verbose = 2,
                      validation_data=(X_cv, y_cv))

Epoch 1/20
336/336 - 14s - 42ms/step - accuracy: 0.9006 - loss: 0.3400 - val_accuracy: 0.9448 - val_loss: 0.1913
Epoch 2/20
336/336 - 9s - 26ms/step - accuracy: 0.9633 - loss: 0.1224 - val_accuracy: 0.9635 - val_loss: 0.1228
Epoch 3/20
336/336 - 11s - 34ms/step - accuracy: 0.9734 - loss: 0.0837 - val_accuracy: 0.9661 - val_loss: 0.1132
Epoch 4/20
336/336 - 11s - 33ms/step - accuracy: 0.9811 - loss: 0.0601 - val_accuracy: 0.9679 - val_loss: 0.1061
Epoch 5/20
336/336 - 11s - 33ms/step - accuracy: 0.9853 - loss: 0.0449 - val_accuracy: 0.9745 - val_loss: 0.0921
Epoch 6/20
336/336 - 10s - 30ms/step - accuracy: 0.9884 - loss: 0.0361 - val_accuracy: 0.9720 - val_loss: 0.1005
Epoch 7/20
336/336 - 9s - 27ms/step - accuracy: 0.9906 - loss: 0.0298 - val_accuracy: 0.9733 - val_loss: 0.0974
Epoch 8/20
336/336 - 10s - 31ms/step - accuracy: 0.9918 - loss: 0.0258 - val_accuracy: 0.9704 - val_loss: 0.1174
Epoch 9/20
336/336 - 11s - 33ms/step - accuracy: 0.9920 - loss: 0.0224 - val_accuracy: 0.9686 - val_loss: 0.1281
Epoch 10/20
336/336 - 10s - 29ms/step - accuracy: 0.9923 - loss: 0.0231 - val_accuracy: 0.9730 - val_loss: 0.1206
Epoch 11/20
336/336 - 11s - 33ms/step - accuracy: 0.9944 - loss: 0.0174 - val_accuracy: 0.9755 - val_loss: 0.1200
Epoch 12/20
336/336 - 11s - 32ms/step - accuracy: 0.9931 - loss: 0.0207 - val_accuracy: 0.9712 - val_loss: 0.1337
Epoch 13/20
336/336 - 11s - 32ms/step - accuracy: 0.9965 - loss: 0.0110 - val_accuracy: 0.9768 - val_loss: 0.1148
Epoch 14/20
336/336 - 10s - 30ms/step - accuracy: 0.9960 - loss: 0.0137 - val_accuracy: 0.9667 - val_loss: 0.1625
Epoch 15/20
336/336 - 12s - 36ms/step - accuracy: 0.9933 - loss: 0.0202 - val_accuracy: 0.9760 - val_loss: 0.1182
Epoch 16/20
336/336 - 9s - 28ms/step - accuracy: 0.9949 - loss: 0.0163 - val_accuracy: 0.9725 - val_loss: 0.1395
Epoch 17/20
336/336 - 10s - 30ms/step - accuracy: 0.9943 - loss: 0.0184 - val_accuracy: 0.9725 - val_loss: 0.1227
Epoch 18/20
336/336 - 12s - 35ms/step - accuracy: 0.9952 - loss: 0.0156 - val_accuracy: 0.9748 - val_loss: 0.1341
Epoch 19/20
336/336 - 9s - 28ms/step - accuracy: 0.9979 - loss: 0.0075 - val_accuracy: 0.9774 - val_loss: 0.1170
Epoch 20/20
336/336 - 10s - 31ms/step - accuracy: 0.9965 - loss: 0.0106 - val_accuracy: 0.9750 - val_loss: 0.1300

In [22]:
#changing learning rate
Inp = Input(shape=(784,))
x = Dense(n_hidden_1, activation='relu', name = "Hidden_Layer_1")(Inp)
x = Dense(n_hidden_2, activation='relu', name = "Hidden_Layer_2")(x)
x = Dense(n_hidden_3, activation='relu', name = "Hidden_Layer_3")(x)
x = Dense(n_hidden_4, activation='relu', name = "Hidden_Layer_4")(x)
output = Dense(num_digits, activation='softmax', name = "Output_Layer")(x)

learning_rate = 0.01
adam = keras.optimizers.Adam(learning_rate=learning_rate)
model2a = Model(Inp, output)

model2a.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [23]:
history2a = model2a.fit(X_train, y_train,
                        batch_size = batch_size,
                        epochs = training_epochs,
                        verbose = 2,
                        validation_data=(X_cv, y_cv))

Epoch 1/20
336/336 - 13s - 38ms/step - accuracy: 0.8942 - loss: 0.3425 - val_accuracy: 0.9510 - val_loss: 0.1575
Epoch 2/20
336/336 - 13s - 38ms/step - accuracy: 0.9624 - loss: 0.1217 - val_accuracy: 0.9652 - val_loss: 0.1083
Epoch 3/20
336/336 - 10s - 29ms/step - accuracy: 0.9749 - loss: 0.0776 - val_accuracy: 0.9663 - val_loss: 0.1118
Epoch 4/20
336/336 - 9s - 28ms/step - accuracy: 0.9820 - loss: 0.0554 - val_accuracy: 0.9706 - val_loss: 0.1061
Epoch 5/20
336/336 - 11s - 32ms/step - accuracy: 0.9843 - loss: 0.0472 - val_accuracy: 0.9719 - val_loss: 0.0920
Epoch 6/20
336/336 - 12s - 36ms/step - accuracy: 0.9886 - loss: 0.0344 - val_accuracy: 0.9731 - val_loss: 0.0927
Epoch 7/20
336/336 - 10s - 29ms/step - accuracy: 0.9913 - loss: 0.0266 - val_accuracy: 0.9750 - val_loss: 0.1012
Epoch 8/20
336/336 - 11s - 33ms/step - accuracy: 0.9927 - loss: 0.0217 - val_accuracy: 0.9719 - val_loss: 0.1023
Epoch 9/20
336/336 - 10s - 30ms/step - accuracy: 0.9926 - loss: 0.0223 - val_accuracy: 0.9762 - val_loss: 0.0985
Epoch 10/20
336/336 - 10s - 31ms/step - accuracy: 0.9913 - loss: 0.0260 - val_accuracy: 0.9739 - val_loss: 0.1116
Epoch 11/20
336/336 - 11s - 32ms/step - accuracy: 0.9940 - loss: 0.0188 - val_accuracy: 0.9701 - val_loss: 0.1215
Epoch 12/20
336/336 - 12s - 37ms/step - accuracy: 0.9943 - loss: 0.0179 - val_accuracy: 0.9714 - val_loss: 0.1243
Epoch 13/20
336/336 - 9s - 27ms/step - accuracy: 0.9943 - loss: 0.0175 - val_accuracy: 0.9652 - val_loss: 0.1501
Epoch 14/20
336/336 - 10s - 31ms/step - accuracy: 0.9956 - loss: 0.0123 - val_accuracy: 0.9782 - val_loss: 0.1019
Epoch 15/20
336/336 - 9s - 26ms/step - accuracy: 0.9966 - loss: 0.0111 - val_accuracy: 0.9751 - val_loss: 0.1216
Epoch 16/20
336/336 - 10s - 29ms/step - accuracy: 0.9950 - loss: 0.0167 - val_accuracy: 0.9776 - val_loss: 0.1032
Epoch 17/20
336/336 - 13s - 37ms/step - accuracy: 0.9948 - loss: 0.0154 - val_accuracy: 0.9725 - val_loss: 0.1354
Epoch 18/20
336/336 - 10s - 29ms/step - accuracy: 0.9979 - loss: 0.0065 - val_accuracy: 0.9773 - val_loss: 0.1236
Epoch 19/20
336/336 - 11s - 32ms/step - accuracy: 0.9966 - loss: 0.0114 - val_accuracy: 0.9762 - val_loss: 0.1266
Epoch 20/20
336/336 - 11s - 33ms/step - accuracy: 0.9955 - loss: 0.0138 - val_accuracy: 0.9773 - val_loss: 0.1226

In [24]:
#changing learning rate again
Inp = Input(shape=(784,))
x = Dense(n_hidden_1, activation='relu', name = "Hidden_Layer_1")(Inp)
x = Dense(n_hidden_2, activation='relu', name = "Hidden_Layer_2")(x)
x = Dense(n_hidden_3, activation='relu', name = "Hidden_Layer_3")(x)
x = Dense(n_hidden_4, activation='relu', name = "Hidden_Layer_4")(x)
output = Dense(num_digits, activation='softmax', name = "Output_Layer")(x)

learning_rate = 0.5
adam = keras.optimizers.Adam(learning_rate=learning_rate)
model2b = Model(Inp, output)

model2b.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [25]:
history2b = model2b.fit(X_train, y_train,
                        batch_size = batch_size,
                        epochs = training_epochs,
                            validation_data=(X_cv, y_cv))

Epoch 1/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 12s 23ms/step - accuracy: 0.8982 - loss: 0.3401 - val_accuracy: 0.9520 - val_loss: 0.1637
Epoch 2/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 9s 20ms/step - accuracy: 0.9617 - loss: 0.1251 - val_accuracy: 0.9575 - val_loss: 0.1324
Epoch 3/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 12s 24ms/step - accuracy: 0.9738 - loss: 0.0821 - val_accuracy: 0.9586 - val_loss: 0.1330
Epoch 4/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 11s 25ms/step - accuracy: 0.9803 - loss: 0.0624 - val_accuracy: 0.9694 - val_loss: 0.1002
Epoch 5/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 16s 40ms/step - accuracy: 0.9868 - loss: 0.0417 - val_accuracy: 0.9726 - val_loss: 0.0984
Epoch 6/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 18s 32ms/step - accuracy: 0.9860 - loss: 0.0418 - val_accuracy: 0.9702 - val_loss: 0.1086
Epoch 7/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 24s 41ms/step - accuracy: 0.9911 - loss: 0.0293 - val_accuracy: 0.9749 - val_loss: 0.0981
Epoch 8/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9920 - loss: 0.0255 - val_accuracy: 0.9727 - val_loss: 0.1017
Epoch 9/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 19s 33ms/step - accuracy: 0.9926 - loss: 0.0226 - val_accuracy: 0.9743 - val_loss: 0.1121
Epoch 10/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 19s 28ms/step - accuracy: 0.9935 - loss: 0.0208 - val_accuracy: 0.9762 - val_loss: 0.1088
Epoch 11/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9942 - loss: 0.0180 - val_accuracy: 0.9760 - val_loss: 0.1181
Epoch 12/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9936 - loss: 0.0197 - val_accuracy: 0.9748 - val_loss: 0.1118
Epoch 13/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 20s 34ms/step - accuracy: 0.9948 - loss: 0.0154 - val_accuracy: 0.9774 - val_loss: 0.1058
Epoch 14/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 21s 34ms/step - accuracy: 0.9937 - loss: 0.0195 - val_accuracy: 0.9757 - val_loss: 0.1256
Epoch 15/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 16s 19ms/step - accuracy: 0.9950 - loss: 0.0161 - val_accuracy: 0.9746 - val_loss: 0.1187
Epoch 16/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 12s 23ms/step - accuracy: 0.9966 - loss: 0.0107 - val_accuracy: 0.9745 - val_loss: 0.1279
Epoch 17/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 11s 24ms/step - accuracy: 0.9966 - loss: 0.0103 - val_accuracy: 0.9752 - val_loss: 0.1476
Epoch 18/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 12s 28ms/step - accuracy: 0.9940 - loss: 0.0187 - val_accuracy: 0.9742 - val_loss: 0.1190
Epoch 19/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 13s 35ms/step - accuracy: 0.9968 - loss: 0.0112 - val_accuracy: 0.9790 - val_loss: 0.1110
Epoch 20/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.9965 - loss: 0.0109 - val_accuracy: 0.9726 - val_loss: 0.1398

In [26]:
# Input Parameters
n_input = 784 # number of features
n_hidden_1 = 300
n_hidden_2 = 100
n_hidden_3 = 100
n_hidden_4 = 100
n_hidden_5 = 200
num_digits = 10

In [27]:
#increasing hidden layer
Inp = Input(shape=(784,))
x = Dense(n_hidden_1, activation='relu', name = "Hidden_Layer_1")(Inp)
x = Dense(n_hidden_2, activation='relu', name = "Hidden_Layer_2")(x)
x = Dense(n_hidden_3, activation='relu', name = "Hidden_Layer_3")(x)
x = Dense(n_hidden_4, activation='relu', name = "Hidden_Layer_4")(x)
x = Dense(n_hidden_5, activation='relu', name = "Hidden_Layer_5")(x)
output = Dense(num_digits, activation='softmax', name = "Output_Layer")(x)

In [28]:
# Our model would have '7' layers - input layer, 5 hidden layer and 1 output layer
model3 = Model(Inp, output)
model3.summary() # We have 308,010 parameters to estimate

Model: "functional_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_5 (InputLayer)      │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_1 (Dense)          │ (None, 300)            │       235,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_2 (Dense)          │ (None, 100)            │        30,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_3 (Dense)          │ (None, 100)            │        10,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_4 (Dense)          │ (None, 100)            │        10,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_5 (Dense)          │ (None, 200)            │        20,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Output_Layer (Dense)            │ (None, 10)             │         2,010 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 308,010 (1.17 MB)

 Trainable params: 308,010 (1.17 MB)

 Non-trainable params: 0 (0.00 B)

In [29]:
# We rely on 'Adam' as our optimizing methodology
adam = keras.optimizers.Adam(learning_rate=0.01)

model3.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [30]:
history3 = model3.fit(X_train, y_train,
                      batch_size = batch_size,
                      epochs = training_epochs,
                      validation_data=(X_cv, y_cv))

Epoch 1/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 20s 30ms/step - accuracy: 0.8869 - loss: 0.3776 - val_accuracy: 0.9514 - val_loss: 0.1640
Epoch 2/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 9s 26ms/step - accuracy: 0.9618 - loss: 0.1264 - val_accuracy: 0.9646 - val_loss: 0.1209
Epoch 3/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 10s 25ms/step - accuracy: 0.9733 - loss: 0.0843 - val_accuracy: 0.9696 - val_loss: 0.1083
Epoch 4/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 13s 32ms/step - accuracy: 0.9804 - loss: 0.0622 - val_accuracy: 0.9669 - val_loss: 0.1106
Epoch 5/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9845 - loss: 0.0504 - val_accuracy: 0.9727 - val_loss: 0.0940
Epoch 6/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9881 - loss: 0.0377 - val_accuracy: 0.9733 - val_loss: 0.0985
Epoch 7/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - accuracy: 0.9892 - loss: 0.0340 - val_accuracy: 0.9727 - val_loss: 0.1024
Epoch 8/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 25s 48ms/step - accuracy: 0.9916 - loss: 0.0286 - val_accuracy: 0.9761 - val_loss: 0.1014
Epoch 9/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 15s 29ms/step - accuracy: 0.9915 - loss: 0.0267 - val_accuracy: 0.9675 - val_loss: 0.1290
Epoch 10/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9917 - loss: 0.0262 - val_accuracy: 0.9765 - val_loss: 0.1041
Epoch 11/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 16s 21ms/step - accuracy: 0.9931 - loss: 0.0216 - val_accuracy: 0.9700 - val_loss: 0.1257
Epoch 12/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 10s 19ms/step - accuracy: 0.9934 - loss: 0.0207 - val_accuracy: 0.9749 - val_loss: 0.1186
Epoch 13/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 11s 22ms/step - accuracy: 0.9940 - loss: 0.0190 - val_accuracy: 0.9755 - val_loss: 0.1122
Epoch 14/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 10s 22ms/step - accuracy: 0.9951 - loss: 0.0157 - val_accuracy: 0.9738 - val_loss: 0.1252
Epoch 15/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 10s 20ms/step - accuracy: 0.9951 - loss: 0.0165 - val_accuracy: 0.9690 - val_loss: 0.1575
Epoch 16/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 11s 23ms/step - accuracy: 0.9950 - loss: 0.0166 - val_accuracy: 0.9762 - val_loss: 0.1189
Epoch 17/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 9s 19ms/step - accuracy: 0.9945 - loss: 0.0171 - val_accuracy: 0.9763 - val_loss: 0.1204
Epoch 18/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 11s 23ms/step - accuracy: 0.9952 - loss: 0.0160 - val_accuracy: 0.9735 - val_loss: 0.1207
Epoch 19/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 11s 23ms/step - accuracy: 0.9958 - loss: 0.0137 - val_accuracy: 0.9787 - val_loss: 0.1037
Epoch 20/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 9s 26ms/step - accuracy: 0.9972 - loss: 0.0096 - val_accuracy: 0.9719 - val_loss: 0.1566

In [31]:
# Input Parameters
n_input = 784 # number of features
n_hidden_1 = 300
n_hidden_2 = 100
n_hidden_3 = 100
n_hidden_4 = 200
num_digits = 10

In [32]:
# Introducing dropout
Inp = Input(shape=(784,))
x = Dense(n_hidden_1, activation='relu', name = "Hidden_Layer_1")(Inp)
x = Dropout(0.3)(x)
x = Dense(n_hidden_2, activation='relu', name = "Hidden_Layer_2")(x)
x = Dropout(0.3)(x)
x = Dense(n_hidden_3, activation='relu', name = "Hidden_Layer_3")(x)
x = Dropout(0.3)(x)
x = Dense(n_hidden_4, activation='relu', name = "Hidden_Layer_4")(x)
output = Dense(num_digits, activation='softmax', name = "Output_Layer")(x)

In [33]:
# Our model would have '6' layers - input layer, 4 hidden layer and 1 output layer
model4 = Model(Inp, output)
model4.summary() # We have 297,910 parameters to estimate

Model: "functional_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_6 (InputLayer)      │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_1 (Dense)          │ (None, 300)            │       235,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 300)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_2 (Dense)          │ (None, 100)            │        30,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 100)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_3 (Dense)          │ (None, 100)            │        10,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 100)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_4 (Dense)          │ (None, 200)            │        20,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Output_Layer (Dense)            │ (None, 10)             │         2,010 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 297,910 (1.14 MB)

 Trainable params: 297,910 (1.14 MB)

 Non-trainable params: 0 (0.00 B)

In [34]:
model4.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [35]:
history = model4.fit(X_train, y_train,
                    batch_size = batch_size,
                    epochs = training_epochs,
                    validation_data=(X_cv, y_cv))

Epoch 1/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 39s 40ms/step - accuracy: 0.8135 - loss: 0.5864 - val_accuracy: 0.9374 - val_loss: 0.2063
Epoch 2/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9303 - loss: 0.2347 - val_accuracy: 0.9570 - val_loss: 0.1495
Epoch 3/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 13s 39ms/step - accuracy: 0.9494 - loss: 0.1713 - val_accuracy: 0.9654 - val_loss: 0.1169
Epoch 4/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9585 - loss: 0.1416 - val_accuracy: 0.9696 - val_loss: 0.1109
Epoch 5/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 19s 36ms/step - accuracy: 0.9633 - loss: 0.1230 - val_accuracy: 0.9690 - val_loss: 0.1117
Epoch 6/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9654 - loss: 0.1143 - val_accuracy: 0.9737 - val_loss: 0.0893
Epoch 7/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 10s 30ms/step - accuracy: 0.9700 - loss: 0.0981 - val_accuracy: 0.9738 - val_loss: 0.0966
Epoch 8/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 12s 34ms/step - accuracy: 0.9719 - loss: 0.0926 - val_accuracy: 0.9748 - val_loss: 0.0852
Epoch 9/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9747 - loss: 0.0842 - val_accuracy: 0.9748 - val_loss: 0.0935
Epoch 10/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 19s 30ms/step - accuracy: 0.9755 - loss: 0.0808 - val_accuracy: 0.9768 - val_loss: 0.0876
Epoch 11/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 12s 33ms/step - accuracy: 0.9788 - loss: 0.0694 - val_accuracy: 0.9765 - val_loss: 0.0902
Epoch 12/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 22s 35ms/step - accuracy: 0.9805 - loss: 0.0649 - val_accuracy: 0.9761 - val_loss: 0.0937
Epoch 13/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 19s 30ms/step - accuracy: 0.9823 - loss: 0.0576 - val_accuracy: 0.9762 - val_loss: 0.0941
Epoch 14/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 12s 31ms/step - accuracy: 0.9827 - loss: 0.0583 - val_accuracy: 0.9790 - val_loss: 0.0954
Epoch 15/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 12s 36ms/step - accuracy: 0.9841 - loss: 0.0531 - val_accuracy: 0.9787 - val_loss: 0.0841
Epoch 16/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 19s 31ms/step - accuracy: 0.9830 - loss: 0.0551 - val_accuracy: 0.9793 - val_loss: 0.0834
Epoch 17/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 12s 34ms/step - accuracy: 0.9834 - loss: 0.0537 - val_accuracy: 0.9793 - val_loss: 0.0889
Epoch 18/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 20s 31ms/step - accuracy: 0.9860 - loss: 0.0471 - val_accuracy: 0.9789 - val_loss: 0.0921
Epoch 19/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9854 - loss: 0.0469 - val_accuracy: 0.9785 - val_loss: 0.0979
Epoch 20/20
336/336 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - accuracy: 0.9859 - loss: 0.0464 - val_accuracy: 0.9813 - val_loss: 0.0876

In [ ]:
# compiled code
# test_pred = pd.DataFrame(model4.predict(X_test, batch_size=200))# The model outputs a matrix of predicted probabilities (shape: (num_samples, num_digits)).
# test_pred = pd.DataFrame(test_pred.idxmax(axis = 1)) #finds the index (column name) of the maximum value in each row — i.e. the predicted class.
# test_pred.index.name = 'ImageId'
# test_pred = test_pred.rename(columns = {0: 'Label'}).reset_index()
# test_pred['ImageId'] = test_pred['ImageId'] + 1

# test_pred.head()

In [37]:
test_pred = pd.DataFrame(model4.predict(X_test, batch_size=200))# The model outputs a matrix of predicted probabilities (shape: (num_samples, num_digits)).
test_pred

140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step

,0,1,2,3,4,5,6,7,8,9
0,1.825147e-15,3.617915e-13,1.000000e+00,3.780278e-11,8.882707e-15,6.627863e-20,1.203247e-14,4.484978e-11,6.608322e-13,1.360766e-19
1,1.000000e+00,2.579485e-20,6.968485e-13,6.242135e-14,7.200484e-16,1.331539e-11,1.276410e-11,5.108465e-13,6.304005e-14,5.123920e-11
2,3.637673e-07,1.074851e-06,4.509176e-08,8.138727e-06,1.516037e-04,2.700521e-06,3.774079e-09,1.180799e-05,1.344528e-05,9.998109e-01
3,1.928712e-01,7.744109e-06,1.394082e-03,1.981023e-03,8.815499e-04,1.120757e-04,2.045682e-05,2.895462e-04,1.421699e-03,8.010206e-01
4,1.423289e-07,3.073917e-05,2.732338e-04,9.984223e-01,2.264714e-08,7.637864e-05,1.573427e-08,1.011790e-04,1.050629e-03,4.541025e-05
...,...,...,...,...,...,...,...,...,...,...
27995,2.774670e-08,2.802335e-09,4.446631e-10,1.479064e-06,7.750287e-07,3.429275e-08,1.909380e-12,2.849872e-07,2.002601e-07,9.999973e-01
27996,1.282675e-14,5.834601e-13,2.925518e-11,2.063649e-12,3.203412e-12,4.211840e-15,2.185017e-19,9.999989e-01,7.119314e-17,1.030425e-06
27997,3.297754e-17,2.748850e-11,9.358267e-11,1.000000e+00,1.282696e-18,1.961078e-09,6.409764e-19,4.091979e-11,2.059321e-10,5.761397e-11
27998,4.631242e-07,6.752837e-07,4.408151e-08,5.786213e-06,1.840423e-04,1.337721e-06,2.372885e-09,5.828937e-06,8.003721e-06,9.997938e-01
27999,1.351989e-11,1.539558e-09,1.000000e+00,1.801081e-08,7.694558e-11,1.552906e-14,9.173097e-11,1.387604e-08,1.128839e-09,1.034028e-14

In [38]:
test_pred = pd.DataFrame(test_pred.idxmax(axis = 1)) #finds the index (column name) of the maximum value in each row — i.e. the predicted class.
test_pred

       0
0      2
1      0
2      9
3      9
4      3
...   ..
27995  9
27996  7
27997  3
27998  9
27999  2

[28000 rows x 1 columns]

In [39]:
test_pred.index.name = 'ImageId'
test_pred = test_pred.rename(columns = {0: 'Label'}).reset_index()
test_pred

       ImageId  Label
0            0      2
1            1      0
2            2      9
3            3      9
4            4      3
...        ...    ...
27995    27995      9
27996    27996      7
27997    27997      3
27998    27998      9
27999    27999      2

[28000 rows x 2 columns]

In [40]:
test_pred['ImageId'] = test_pred['ImageId'] + 1

test_pred.head()

   ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      9
4        5      3

In [41]:
test_pred.to_csv('mnist_submission.csv', index = False)